types:
    - build
    - deploy

build: 
    type: build
    script:
        - cd frontend
        - npm config set registry https://registry.npmjs.org/
        - npm install 
        - npm run build
        - cd ../backend
        - cargo build --release
        - cd ..
        - docker-compose pull
        - docker-compose build

deploy:
    type: deploy
    script:
        - docker-compose up -d
