types:
    - build
    - deploy

build: 
    type: build
    script:
        - cd frontend
        - npm config set registry https://registry.npmjs.org/
        - npm install 
        - npm run build
        - cd ../backend
        - cargo build --release
        - cd ..

        - mkdir build
        - cp Dockerfile build/
        - cp -r frontend/dist/ build/frontend/
        - cp backend/target/release/backend build/backend
        - cp backend/run_backend.sh build/backend/
        - cp -r database build/database
        - cp -r nginx build/nginx

        - cd build

        - docker-compose pull
        - docker-compose build

deploy:
    type: deploy
    script:
        - docker-compose up -d
