types:
    - setup
    - build
    - deploy

# before_script:

frontend:
    type: setup
    script:
        - cd frontend
        - npm install 
        - npm run build


build: 
    type: build
    script:
        - docker-compose build

deploy:
    type: deploy
    script:
        - docker-compose up -d
