[package]
name = "backend"
version = "0.1.0"
authors = ["dexter <dexter@dexterlabs.nl>", "benjamin <bwb@bwblabs.com>"]

[dependencies]
iron = "*"
router = "*"
rust-crypto = "^0.2"
persistent = "*"
rustc-serialize = "*"
bodyparser = "*"
rand = "*"
time = "*"
