[package]
name = "backend"
version = "0.1.0"
authors = ["dexter <dexter@dexterlabs.nl>", "Benjamin W. Broersma <bw@broersma.com>"]

[dependencies]
iron = "*"
router = "*"
rust-crypto = "^0.2"
persistent = "*"
#rustc-serialize = "*"
#serialize = "*"
postgres = { version = "*", features = ["serde_json"]}
serde = "0.6"
serde_json = "*"
#serde_macros = "*"
bodyparser = "*"
rand = "*"
time = "*"

[dependencies.iron-postgres-middleware]
git = "https://github.com/martinsp/iron-postgres-middleware.git"
