[package]
name = "backend"
version = "0.1.0"
authors = ["dexter <dexter@dexterlabs.nl>", "Benjamin W. Broersma <bw@broersma.com>"]

[dependencies]
iron = "*"
hyper = "*"
router = "*"
persistent = "*"
postgres = { version = "*", features = ["serde_json", "unix_socket"]}
postgres_macros = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
bodyparser = {git = "https://github.com/jimmycuadra/body-parser.git", branch = "serde" } # move to "*" when https://github.com/iron/body-parser/pull/64 gets approved
rand = "*"
time = "*"
rustc-serialize = "*"

[dependencies.iron-postgres-middleware]
git = "https://github.com/neoel/iron-postgres-middleware.git"

[dependencies.logger]

git = "https://github.com/iron/logger.git"