[package]
name = "backend"
version = "0.1.0"
authors = ["dexter <dexter@dexterlabs.nl>", "Benjamin W. Broersma <bw@broersma.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
postgres = { version = "*", features = ["serde_json", "unix_socket"]}
serde = "*"
serde_json = "*"
#serde_macros = "*"
bodyparser = "*"
rand = "*"
time = "*"

[dependencies.iron-postgres-middleware]
git = "https://github.com/neoel/iron-postgres-middleware.git"